default: &default
  adapter: sqlserver
  host: sqlserver2019  # Nombre del contenedor SQL Server
  username: sa
  password: "YourStrong@Passw0rd"
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  port: 1433

development:
  <<: *default
  database: GestionVentas

test:
  <<: *default
  database: GestionVentas_test

production:
  <<: *default
  database: GestionVentas_production